import { createAdminClient } from "./supabase";

// New — this webhook-orchestration layer didn't exist in the source app at
// all (it never had its own webhook; the graph was only ever invoked
// directly, e.g. from LangGraph Studio, with a conversationId already
// supplied by hand). Not a port, just enough plumbing for the webhook route
// to find/start a conversation and log both sides of the turn into the same
// whatsapp_conversations/whatsapp_messages tables the ported graph itself
// reads from (@/lib/db.ts).

export interface ActiveConversation {
  conversationId: string;
  /**
   * True only on the actual insert branch below — this is the one and only
   * "did a brand new conversation just start" signal in this codebase. The
   * webhook route uses it to fire a one-time registerGuestContact() call
   * (@/lib/crm.ts) on a guest's very first inbound message, without
   * re-registering them on every subsequent turn of an already-active
   * conversation.
   */
  isNew: boolean;
}

/**
 * Finds the guest's currently-active conversation, or starts a new one.
 *
 * Phone form reconciliation: Twilio's inbound webhook always stores
 * whatsapp_conversations.phone_number with a "whatsapp:" prefix (the raw
 * `From` field, passed straight through by
 * apps/.../api/webhook/whatsapp/route.ts). Other callers — notably POST
 * /api/send's proactive sends — pass the bare/normalized form instead (e.g.
 * "+351920742845", CRM's stored form). Looking the existing row up with a
 * plain `.eq("phone_number", phone)` therefore missed a guest's real active
 * conversation whenever it was stored under the other form, silently
 * creating a second, disconnected conversation row instead — the same
 * "check both forms" reconciliation GET /api/conversations already does for
 * reads (see that route's own doc comment) is applied here for the
 * find-or-create write path too. `phoneForms` is deduped so an
 * already-prefixed `phone` (the inbound webhook's case today) doesn't pass
 * the same value twice into `.in(...)` — harmless for Postgres either way,
 * but avoids the redundant array entry.
 *
 * When no existing conversation is found under either form, the new row is
 * inserted under the prefixed form specifically (not whatever raw form was
 * passed in) — so a bare-form caller like POST /api/send converges on the
 * same stored form the inbound webhook already uses, and a guest's future
 * reply (which always arrives prefixed, via Twilio) finds this conversation
 * instead of fragmenting it further.
 *
 * Deliberately `.order(...).limit(1)` rather than `.maybeSingle()` alone on
 * the raw `.in(...)` query: exactly this fragmentation bug can (and, in
 * practice while diagnosing it, did) leave more than one row "active" for
 * the same guest under different stored phone forms. An unqualified
 * `.maybeSingle()` errors out on >1 row, which — if that error goes
 * unchecked — falls through to the insert branch and creates yet another
 * duplicate, compounding the exact problem this fix exists to stop. Taking
 * the most-recently-started active row instead degrades gracefully in that
 * already-fragmented state (same "most recent first" convention GET
 * /api/conversations already orders by) while behaving identically to
 * before when only one active row exists, which is the normal case.
 */
export async function getOrCreateActiveConversation(phone: string): Promise<ActiveConversation> {
  const supabase = createAdminClient();

  const prefixedPhone = phone.startsWith("whatsapp:") ? phone : `whatsapp:${phone}`;
  const phoneForms = Array.from(new Set([phone, prefixedPhone]));

  const { data: existing } = await supabase
    .from("whatsapp_conversations")
    .select("id")
    .in("phone_number", phoneForms)
    .eq("status", "active")
    .order("started_at", { ascending: false })
    .limit(1)
    .maybeSingle();
  if (existing) {
    return { conversationId: existing.id, isNew: false };
  }

  const { data: created, error } = await supabase
    .from("whatsapp_conversations")
    .insert({ phone_number: prefixedPhone })
    .select("id")
    .single();
  if (error || !created) {
    throw new Error(`Failed to create whatsapp_conversation for ${phone}: ${error?.message}`);
  }
  return { conversationId: created.id, isNew: true };
}

/**
 * `langsmithRunId` is optional and only ever present for an assistant reply
 * generated by the webhook route's own graph.invoke() call (see that
 * route's own doc comment for how the id is fixed up front). A guest's
 * inbound message and a proactive/campaign send (POST /api/send, which
 * never touches the graph) have no real trace to attach, so both callers
 * simply omit this argument — the insert then omits the column entirely
 * (rather than writing an explicit `null`), matching
 * whatsapp_messages.langsmith_run_id's own nullable, "no value" convention.
 */
export async function recordMessage(
  conversationId: string,
  role: "user" | "assistant",
  content: string,
  langsmithRunId?: string,
): Promise<void> {
  const supabase = createAdminClient();
  const insert: Record<string, unknown> = { conversation_id: conversationId, role, content };
  if (langsmithRunId !== undefined) {
    insert.langsmith_run_id = langsmithRunId;
  }
  const { error } = await supabase.from("whatsapp_messages").insert(insert);
  if (error) {
    throw new Error(
      `Failed to record ${role} message for conversation ${conversationId}: ${error.message}`,
    );
  }
}
