import type { PatternMeta } from "./schema";

type SlugAndMeta = { slug: string; meta: PatternMeta };

function section(heading: string, docs: readonly SlugAndMeta[]): string[] {
  const lines = [...docs]
    .sort((a, b) => (a.slug < b.slug ? -1 : a.slug > b.slug ? 1 : 0))
    .map(({ slug, meta }) => `- [${meta.title}](content/${slug}.mdx) — read when: ${meta.summary}`);
  return [`## ${heading}`, "", ...(lines.length > 0 ? lines : ["None yet."]), ""];
}

/**
 * The text of `content/INDEX.md`: every doc as one "read when" line, in the
 * style of `docs/conditional-docs.md`. The em dash in each line is that file's
 * index syntax, not prose. Written to be prettier-stable as-is.
 */
export function renderIndexMd(docs: readonly SlugAndMeta[]): string {
  return [
    "# Pattern index",
    "",
    "Generated by `yarn workspace patterns index` from the frontmatter of every doc in `content/`. Do not edit by hand. Paths are relative to `apps/patterns/`.",
    "",
    ...section(
      "Atoms",
      docs.filter((doc) => doc.meta.kind === "atom"),
    ),
    ...section(
      "Composites",
      docs.filter((doc) => doc.meta.kind === "composite"),
    ),
  ].join("\n");
}
