// Generated by `yarn workspace patterns index` from the files in content/.
// Do not edit by hand; the registry validates every entry at module scope.
import * as doc0 from "@content/infinite-scrolling.mdx";
import * as doc1 from "@content/server-prefetch-hydration.mdx";
import * as doc2 from "@content/sse-route-handler.mdx";
import * as doc3 from "@content/suspense-without-flash.mdx";
import * as doc4 from "@content/use-sync-external-store.mdx";

export const manifest = [
  {
    slug: "infinite-scrolling",
    meta: doc0.frontmatter,
    Content: doc0.default,
  },
  {
    slug: "server-prefetch-hydration",
    meta: doc1.frontmatter,
    Content: doc1.default,
  },
  {
    slug: "sse-route-handler",
    meta: doc2.frontmatter,
    Content: doc2.default,
  },
  {
    slug: "suspense-without-flash",
    meta: doc3.frontmatter,
    Content: doc3.default,
  },
  {
    slug: "use-sync-external-store",
    meta: doc4.frontmatter,
    Content: doc4.default,
  },
] as const;
