/**
 * The source text of `manifest.generated.ts`: one explicit import per doc, so
 * the bundler resolves every doc at build time and no route ever reads the
 * content directory. Namespace imports and one-key-per-line objects keep the
 * output prettier-stable as written, whatever the slug length.
 */
export function renderManifest(slugs: readonly string[]): string {
  const sorted = [...slugs].sort();
  const imports = sorted.map(
    (slug, index) => `import * as doc${index} from "@content/${slug}.mdx";`,
  );
  const entries = sorted.map((slug, index) =>
    [
      "  {",
      `    slug: "${slug}",`,
      `    meta: doc${index}.frontmatter,`,
      `    Content: doc${index}.default,`,
      "  },",
    ].join("\n"),
  );

  return [
    "// Generated by `yarn workspace patterns index` from the files in content/.",
    "// Do not edit by hand; the registry validates every entry at module scope.",
    ...imports,
    "",
    ...(entries.length === 0
      ? ["export const manifest = [] as const;"]
      : ["export const manifest = [", ...entries, "] as const;"]),
    "",
  ].join("\n");
}
