// Generated by `yarn workspace patterns index` from the files in content/.
// Do not edit by hand; the registry validates every entry at module scope.
import * as doc0 from "@content/agent-memory-window.mdx";
import * as doc1 from "@content/agent-release-gate.mdx";
import * as doc2 from "@content/approval-gate-wait-for-event.mdx";
import * as doc3 from "@content/durable-agent-turn.mdx";
import * as doc4 from "@content/eval-gate-independent-thresholds.mdx";
import * as doc5 from "@content/flush-before-freeze.mdx";
import * as doc6 from "@content/fold-and-distill-memory.mdx";
import * as doc7 from "@content/human-gated-tool.mdx";
import * as doc8 from "@content/idempotent-write-by-trace-key.mdx";
import * as doc9 from "@content/in-band-correlation.mdx";
import * as doc10 from "@content/infinite-scrolling.mdx";
import * as doc11 from "@content/manual-tool-loop.mdx";
import * as doc12 from "@content/sandboxed-tool-shims.mdx";
import * as doc13 from "@content/server-prefetch-hydration.mdx";
import * as doc14 from "@content/sse-route-handler.mdx";
import * as doc15 from "@content/step-memoized-side-effects.mdx";
import * as doc16 from "@content/suspense-without-flash.mdx";
import * as doc17 from "@content/tool-file-convention.mdx";
import * as doc18 from "@content/trace-anchor-across-steps.mdx";
import * as doc19 from "@content/turn-replay-history.mdx";
import * as doc20 from "@content/use-action-state.mdx";
import * as doc21 from "@content/use-sync-external-store.mdx";

export const manifest = [
  {
    slug: "agent-memory-window",
    meta: doc0.frontmatter,
    Content: doc0.default,
  },
  {
    slug: "agent-release-gate",
    meta: doc1.frontmatter,
    Content: doc1.default,
  },
  {
    slug: "approval-gate-wait-for-event",
    meta: doc2.frontmatter,
    Content: doc2.default,
  },
  {
    slug: "durable-agent-turn",
    meta: doc3.frontmatter,
    Content: doc3.default,
  },
  {
    slug: "eval-gate-independent-thresholds",
    meta: doc4.frontmatter,
    Content: doc4.default,
  },
  {
    slug: "flush-before-freeze",
    meta: doc5.frontmatter,
    Content: doc5.default,
  },
  {
    slug: "fold-and-distill-memory",
    meta: doc6.frontmatter,
    Content: doc6.default,
  },
  {
    slug: "human-gated-tool",
    meta: doc7.frontmatter,
    Content: doc7.default,
  },
  {
    slug: "idempotent-write-by-trace-key",
    meta: doc8.frontmatter,
    Content: doc8.default,
  },
  {
    slug: "in-band-correlation",
    meta: doc9.frontmatter,
    Content: doc9.default,
  },
  {
    slug: "infinite-scrolling",
    meta: doc10.frontmatter,
    Content: doc10.default,
  },
  {
    slug: "manual-tool-loop",
    meta: doc11.frontmatter,
    Content: doc11.default,
  },
  {
    slug: "sandboxed-tool-shims",
    meta: doc12.frontmatter,
    Content: doc12.default,
  },
  {
    slug: "server-prefetch-hydration",
    meta: doc13.frontmatter,
    Content: doc13.default,
  },
  {
    slug: "sse-route-handler",
    meta: doc14.frontmatter,
    Content: doc14.default,
  },
  {
    slug: "step-memoized-side-effects",
    meta: doc15.frontmatter,
    Content: doc15.default,
  },
  {
    slug: "suspense-without-flash",
    meta: doc16.frontmatter,
    Content: doc16.default,
  },
  {
    slug: "tool-file-convention",
    meta: doc17.frontmatter,
    Content: doc17.default,
  },
  {
    slug: "trace-anchor-across-steps",
    meta: doc18.frontmatter,
    Content: doc18.default,
  },
  {
    slug: "turn-replay-history",
    meta: doc19.frontmatter,
    Content: doc19.default,
  },
  {
    slug: "use-action-state",
    meta: doc20.frontmatter,
    Content: doc20.default,
  },
  {
    slug: "use-sync-external-store",
    meta: doc21.frontmatter,
    Content: doc21.default,
  },
] as const;
